micronaut:
  application:
    name: rimfirejwt
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
  server:
    port: 5555
datasources:
  default:
    url: jdbc:oracle:thin:@localhost:4521:RFDV2
    driver-class-name: oracle.jdbc.OracleDriver
    username: dsrsuser
    password: dsrs8CAFA4
    schema-generate: CREATE_DROP
    dialect: ORACLE
    current-schema: DSRUSER