micronaut:
  application:
    name: rimfirejwt
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
datasources:
  default:
    driver-class-name: oracle.jdbc.OracleDriver
    db-type: oracle
    schema-generate: CREATE_DROP
    dialect: ORACLE
